# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96fbf5f97efdc2bc22d1426729a9457874caeb68844646e9ba66274ca96c1c79af5d8fd68a13ad755a35029edf891a71642ae48cd8805f8ca6062370c5d6fab6

test:
  secret_key_base: 89ba3c8c7c6e187c252f8576de215847bd1ec3e5722d5b41d710fcac49eaa31138831cd0fa74705ff987fb369ef47b95b51b78df8ccab025c9579a91bd6dd6f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
